# Generated by Django 4.2.6 on 2023-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='imagesPizzas/default.png', upload_to='imagesPizzas/'),
        ),
    ]
