# Generated by Django 5.0 on 2023-12-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicompte', '0001_initial'),
        ('applipizza', '0002_pizza_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.AutoField(primary_key=True, serialize=False)),
                ('dateCommande', models.DateField(auto_now_add=True)),
                ('payee', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='le prix')),
                ('pizzauser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicompte.pizzauser')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('idLigneCommande', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='la quantité de pizza')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='le prix')),
                ('commande_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applipanier.commande')),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applipizza.pizza')),
            ],
        ),
    ]
