# Generated by Django 4.2.7 on 2023-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applipanier', '0002_rename_pizzauser_id_commande_pizzauser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='le prix'),
        ),
    ]
